/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */

/* LA32R pt_regs offsets. */
#define PT_R0 0 /* offsetof(struct pt_regs, regs[0])	 # */
#define PT_R1 4 /* offsetof(struct pt_regs, regs[1])	 # */
#define PT_R2 8 /* offsetof(struct pt_regs, regs[2])	 # */
#define PT_R3 12 /* offsetof(struct pt_regs, regs[3])	 # */
#define PT_R4 16 /* offsetof(struct pt_regs, regs[4])	 # */
#define PT_R5 20 /* offsetof(struct pt_regs, regs[5])	 # */
#define PT_R6 24 /* offsetof(struct pt_regs, regs[6])	 # */
#define PT_R7 28 /* offsetof(struct pt_regs, regs[7])	 # */
#define PT_R8 32 /* offsetof(struct pt_regs, regs[8])	 # */
#define PT_R9 36 /* offsetof(struct pt_regs, regs[9])	 # */
#define PT_R10 40 /* offsetof(struct pt_regs, regs[10])	 # */
#define PT_R11 44 /* offsetof(struct pt_regs, regs[11])	 # */
#define PT_R12 48 /* offsetof(struct pt_regs, regs[12])	 # */
#define PT_R13 52 /* offsetof(struct pt_regs, regs[13])	 # */
#define PT_R14 56 /* offsetof(struct pt_regs, regs[14])	 # */
#define PT_R15 60 /* offsetof(struct pt_regs, regs[15])	 # */
#define PT_R16 64 /* offsetof(struct pt_regs, regs[16])	 # */
#define PT_R17 68 /* offsetof(struct pt_regs, regs[17])	 # */
#define PT_R18 72 /* offsetof(struct pt_regs, regs[18])	 # */
#define PT_R19 76 /* offsetof(struct pt_regs, regs[19])	 # */
#define PT_R20 80 /* offsetof(struct pt_regs, regs[20])	 # */
#define PT_R21 84 /* offsetof(struct pt_regs, regs[21])	 # */
#define PT_R22 88 /* offsetof(struct pt_regs, regs[22])	 # */
#define PT_R23 92 /* offsetof(struct pt_regs, regs[23])	 # */
#define PT_R24 96 /* offsetof(struct pt_regs, regs[24])	 # */
#define PT_R25 100 /* offsetof(struct pt_regs, regs[25])	 # */
#define PT_R26 104 /* offsetof(struct pt_regs, regs[26])	 # */
#define PT_R27 108 /* offsetof(struct pt_regs, regs[27])	 # */
#define PT_R28 112 /* offsetof(struct pt_regs, regs[28])	 # */
#define PT_R29 116 /* offsetof(struct pt_regs, regs[29])	 # */
#define PT_R30 120 /* offsetof(struct pt_regs, regs[30])	 # */
#define PT_R31 124 /* offsetof(struct pt_regs, regs[31])	 # */
#define PT_SIZE 136 /* sizeof(struct pt_regs)	 # */


#endif
